### ISSUE TITLE
Application stuck

### ISSUE THREAD

**Issue by nuhamind2** [lcherone/lxd-ui#1]
Haven't succesfully use lxd-ui
OS : Ubuntu Zesty 64 bit
lxd-ui version  = 0.0.5
lxc --version = 2.12
Problem : dashboard only displaying spinning cursor

Tried with normal user and sudo

**Comment by nuhamind2** [comment]
Yes I have, this the output from lxd cli
```bash
nuha@nuha-X455LN:~$ lxc ls
+------+---------+------+------+------------+-----------+
| NAME |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+------+---------+------+------+------------+-----------+
| vm   | STOPPED |      |      | PERSISTENT | 0         |
+------+---------+------+------+------------+-----------+
nuha@nuha-X455LN:~$ lxc image ls
+-------+--------------+--------+-----------------------------------+--------+--------+------------------------------+
| ALIAS | FINGERPRINT  | PUBLIC |            DESCRIPTION            |  ARCH  |  SIZE  |         UPLOAD DATE          |
+-------+--------------+--------+-----------------------------------+--------+--------+------------------------------+
|       | 419ccf8e81ff | no     | Alpine 3.7 amd64 (20180325_17:50) | x86_64 | 1.80MB | Mar 26, 2018 at 3:09am (UTC) |
+-------+--------------+--------+-----------------------------------+--------+--------+------------------------------+
nuha@nuha-X455LN:~$ 
```bash

**Comment by nuhamind2** [comment]
![image](https://user-images.githubusercontent.com/6321488/38454046-eed68b42-3a89-11e8-9690-68cf028c19e9.png)
You can see that lxd-ui actually detecting that I have 1 image, but it's stuck spinning like that

**Comment by lcherone** [comment]
Yeah something is up, what I have done is added the option to open devtools, download [version 0.0.6](https://github.com/lcherone/lxd-ui/releases/tag/0.0.6a) and then you should be able to press `Ctrl-x` and it will open dev tools, then it will ive me a better idea as to why its not working for you. send me a screen..

cheers.

**Comment by lcherone** [comment]
I think it will be fixed now as I've removed a call to `resources` endpoint (but not actually using) which was introduced in version LXD 2.19. https://discuss.linuxcontainers.org/t/lxd-2-19-has-been-released/665 your using 2.12, it was most likely borking out on that.

**Comment by nuhamind2** [comment]
The problem still persist using 0.0.7
I attach the log from console tab.
[-1523118289504.log](https://github.com/lcherone/lxd-ui/files/1886538/-1523118289504.log)

**Comment by lcherone** [comment]
thanks, sorry I can see from that log `lxc query` is not in your version, it was added in LXD 2.17.. your need to update to use the app as it uses `lxc query` almost throughout, LXD is at 3.0 now.

**Comment by nuhamind2** [comment]
I think I got deeper in a rabbit hole.

I update to lxd 3.0 through snap, and LXDUi now simply a blank white screen, tried with 0.0.5 , 0.0.6 and 0.0.7.
Console didn't show anything

I think my lxd installation is fine, lxc query work and I also tried web based gui from AdaptiveScale, which is working.

```bash
nuha@nuha-X455LN:~$ lxc query -X GET  '/1.0/profiles'
[
	"/1.0/profiles/default"
]
nuha@nuha-X455LN:~$ 
```

**Comment by lcherone** [comment]
I cant think of a reason v0.0.7 would white screen without errors, I'm using right now without issues and generally if electron is missing a dependency it just wont startup + if its a javascript issue you would see it in the console and as the interface is reactive, you would just get spinners (like you originally got) if something breaks half way.

I'm on 16.04 using version 3.0 snap and its working fine, I've tested it on 17.04 and the new 18.04 (which prompted me to report this: https://github.com/lxc/lxd/issues/4406). Though I use xfce not unity but im not sure if that matters as it wouldn't cause electron to bork out. Can you run stuff like atom editor, slack etc?

Try 0.0.8 and choose No when it asks you to integrate it into your system. Or perhaps try with https://github.com/lcherone/lxd-ui#developer-setup as it might let on as to why it's white screening.

Sorry cant help much more then that..

**Comment by nuhamind2** [comment]
It's okay, thanks for the effort.
I'll try digging deeper and report back on any finding. I can run slack, vscode and discord

**Comment by nuhamind2** [comment]
Just putting in here in case someone stumble upon this. My lxd-ui finally run correctly (no more white blank screen), but I don't remember doing anything except reinstalling lxd.

**Comment by lcherone** [comment]
I encountered this issue on my laptop tonight and tracked it down.

You must remove the old lxc client as seems to conflict with the snap package directly after install.

`sudo apt remove lxd lxd-client`

then install the snap.

```
# setup LXD group
sudo groupadd --system lxd
sudo usermod -a -G lxd $USER
# install lxd
sudo apt-get --yes install snapd
sudo snap install lxd
sudo lxd waitready
sudo lxd init
```

Then it works fine.

**Comment by wmchris** [comment]
i have the same issue, but installed with snap from the beginning. debian 9 based system with lxde4 as gui. running LXDUI with dev from source works fine, but as soon as i build it, it doesnt work anymore.
