### ISSUE TITLE
Remote server control

### ISSUE THREAD

**Issue by talyguryn** [lcherone/LXD-UI#3]
Is it possible to set up connection to remove server? Then you can make a cross-platform app as real lxd ui.

**Comment by lcherone** [comment]
No, as mentioned in the previous issue #2 cross server is not possible, though you can add a remote as you would normally do `lxc add remote` and it will show up in the images page, then you can pull images from that remote, but no its not a multi-server system as mentioned in the readme.

You might be interested in a new project I've built this week which is multi-server, though it's aimed at web development/hosting: https://github.com/lcherone/Deval
