### ISSUE TITLE
It is possible to edit configuration to point to my snap installation?

### ISSUE THREAD

**Issue by averyfreeman** [lcherone/LXD-UI#7]
Hi, 

great project!  I am not seeing it interface with LXD, though

Is it possible to edit a config file so it points to /snap/bin/lxd ?

Thank you

**Comment by lcherone** [comment]
He there is a not in the readme in issue section:

> The app does not check for `lxd.lxc` but instead expects the standard lxc commands to hit the correct binary.

So uninstall upstream lxd then install the snap, its a path issue.
