### ISSUE TITLE
Can't start appimage

### ISSUE THREAD

**Issue by tgeek77** [lcherone/lxd-ui#8]
OS: OpenSUSE Tumbleweed

```
$ chmod +x LXDui-1.0.0-x86_64.AppImage
$ ./LXDui-1.0.0-x86_64.AppImage 

(lxdui:14706): Pango-ERROR **: 22:46:18.874: Harfbuzz version too old (1.4.2)
```

Trace/breakpoint trap (core dumped)

**Comment by lcherone** [comment]
See: https://github.com/electron/electron/issues/20348

**Comment by lcherone** [comment]
Additionally.. I used a fixed version of electron as anything above see version: https://github.com/lcherone/LXD-UI/blob/master/package.json#L97 it performed poorly when rendering causing the terminal/console to flicker like buggery.
