### ISSUE TITLE
Does not work with node v10.19.0

### ISSUE THREAD

**Issue by gglp** [lcherone/lxd-ui#9]
.AppImage generate error: cannot execute binary file
npm build generates a lot of errors

**Comment by lcherone** [comment]
please share the errors, thanks

you may need to update some packages, its been a while since working on this project packages will be out of date

**Comment by gglp** [comment]
fedorov@bequiet:~/LXD-UI$ npm install

> bufferutil@3.0.3 install /home/fedorov/LXD-UI/node_modules/bufferutil
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.3.0
prebuild-install info looking for local prebuild @ prebuilds/bufferutil-v3.0.3-node-v64-linux-x64.tar.gz
prebuild-install info looking for cached prebuild @ /home/fedorov/.npm/_prebuilds/https-github.com-websockets-bufferutil-releases-download-v3.0.3-bufferutil-v3.0.3-node-v64-linux-x64.tar.gz
prebuild-install http request GET https://github.com/websockets/bufferutil/releases/download/v3.0.3/bufferutil-v3.0.3-node-v64-linux-x64.tar.gz
prebuild-install http 404 https://github.com/websockets/bufferutil/releases/download/v3.0.3/bufferutil-v3.0.3-node-v64-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=10.19.0 runtime=node arch=x64 platform=linux)
make: вход в каталог «/home/fedorov/LXD-UI/node_modules/bufferutil/build»
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
In file included from ../node_modules/nan/nan.h:192,
                 from ../src/bufferutil.cc:7:
../node_modules/nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../node_modules/nan/nan_maybe_43_inl.h:112:15: error: ‘class v8::Object’ has no member named ‘ForceSet’
  112 |   return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
      |               ^~~~~~~~
In file included from ../src/bufferutil.cc:7:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’:
../node_modules/nan/nan.h:835:60: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
  835 |         v8::Isolate::GetCurrent(), target, func, argc, argv);
      |                                                            ^
In file included from ../node_modules/nan/nan.h:49,
                 from ../src/bufferutil.cc:7:
/usr/include/nodejs/src/node.h:177:50: note: declared here
  177 |                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
      |                                                  ^~~~~~~~~~~~
/usr/include/nodejs/src/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
   91 |     __attribute__((deprecated(message))) declarator
      |                                          ^~~~~~~~~~
In file included from ../src/bufferutil.cc:7:
../node_modules/nan/nan.h:835:60: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
  835 |         v8::Isolate::GetCurrent(), target, func, argc, argv);
      |                                                            ^
In file included from ../node_modules/nan/nan.h:49,
                 from ../src/bufferutil.cc:7:
/usr/include/nodejs/src/node.h:177:50: note: declared here
  177 |                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
      |                                                  ^~~~~~~~~~~~
/usr/include/nodejs/src/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
   91 |     __attribute__((deprecated(message))) declarator
      |                                          ^~~~~~~~~~
In file included from ../src/bufferutil.cc:7:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’:
../node_modules/nan/nan.h:850:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
  850 |         v8::Isolate::GetCurrent(), target, symbol, argc, argv);
      |                                                              ^
In file included from ../node_modules/nan/nan.h:49,
                 from ../src/bufferutil.cc:7:
/usr/include/nodejs/src/node.h:170:50: note: declared here
  170 |                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
      |                                                  ^~~~~~~~~~~~
/usr/include/nodejs/src/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
   91 |     __attribute__((deprecated(message))) declarator
      |                                          ^~~~~~~~~~
In file included from ../src/bufferutil.cc:7:
../node_modules/nan/nan.h:850:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
  850 |         v8::Isolate::GetCurrent(), target, symbol, argc, argv);
      |                                                              ^
In file included from ../node_modules/nan/nan.h:49,
                 from ../src/bufferutil.cc:7:
/usr/include/nodejs/src/node.h:170:50: note: declared here
  170 |                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
      |                                                  ^~~~~~~~~~~~
/usr/include/nodejs/src/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
   91 |     __attribute__((deprecated(message))) declarator
      |                                          ^~~~~~~~~~
In file included from ../src/bufferutil.cc:7:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’:
../node_modules/nan/nan.h:865:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
  865 |         v8::Isolate::GetCurrent(), target, method, argc, argv);
      |                                                              ^
In file included from ../node_modules/nan/nan.h:49,
                 from ../src/bufferutil.cc:7:
/usr/include/nodejs/src/node.h:163:50: note: declared here
  163 |                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
      |                                                  ^~~~~~~~~~~~
/usr/include/nodejs/src/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
   91 |     __attribute__((deprecated(message))) declarator
      |                                          ^~~~~~~~~~
In file included from ../src/bufferutil.cc:7:
../node_modules/nan/nan.h:865:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
  865 |         v8::Isolate::GetCurrent(), target, method, argc, argv);
      |                                                              ^
In file included from ../node_modules/nan/nan.h:49,
                 from ../src/bufferutil.cc:7:
/usr/include/nodejs/src/node.h:163:50: note: declared here
  163 |                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
      |                                                  ^~~~~~~~~~~~
/usr/include/nodejs/src/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
   91 |     __attribute__((deprecated(message))) declarator
      |                                          ^~~~~~~~~~
In file included from ../src/bufferutil.cc:7:
../node_modules/nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const’:
../node_modules/nan/nan.h:1479:5: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
 1479 |     ));
      |     ^
In file included from ../node_modules/nan/nan.h:49,
                 from ../src/bufferutil.cc:7:
/usr/include/nodejs/src/node.h:177:50: note: declared here
  177 |                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
      |                                                  ^~~~~~~~~~~~
/usr/include/nodejs/src/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
   91 |     __attribute__((deprecated(message))) declarator
      |                                          ^~~~~~~~~~
In file included from ../src/bufferutil.cc:7:
../node_modules/nan/nan.h:1479:5: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
 1479 |     ));
      |     ^
In file included from ../node_modules/nan/nan.h:49,
                 from ../src/bufferutil.cc:7:
/usr/include/nodejs/src/node.h:177:50: note: declared here
  177 |                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
      |                                                  ^~~~~~~~~~~~
/usr/include/nodejs/src/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
   91 |     __attribute__((deprecated(message))) declarator
      |                                          ^~~~~~~~~~
In file included from ../src/bufferutil.cc:7:
../node_modules/nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../node_modules/nan/nan.h:1732:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
 1732 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
../src/bufferutil.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE mask(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/bufferutil.cc:12:64: warning: ‘int32_t v8::Value::Int32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   12 |   char* to = node::Buffer::Data(info[2]) + info[3]->Int32Value();
      |                                                                ^
In file included from /usr/include/nodejs/deps/v8/include/v8.h:26,
                 from /usr/include/nodejs/src/node.h:63,
                 from ../node_modules/nan/nan.h:49,
                 from ../src/bufferutil.cc:7:
/usr/include/nodejs/deps/v8/include/v8.h:2478:46: note: declared here
 2478 |   V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
      |                                              ^~~~~~~~~~
/usr/include/nodejs/deps/v8/include/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
  324 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
../src/bufferutil.cc:13:39: warning: ‘int32_t v8::Value::Int32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   13 |   size_t length = info[4]->Int32Value();
      |                                       ^
In file included from /usr/include/nodejs/deps/v8/include/v8.h:26,
                 from /usr/include/nodejs/src/node.h:63,
                 from ../node_modules/nan/nan.h:49,
                 from ../src/bufferutil.cc:7:
/usr/include/nodejs/deps/v8/include/v8.h:2478:46: note: declared here
 2478 |   V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
      |                                              ^~~~~~~~~~
/usr/include/nodejs/deps/v8/include/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
  324 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
In file included from ../node_modules/nan/nan.h:49,
                 from ../src/bufferutil.cc:7:
../src/bufferutil.cc: At global scope:
/usr/include/nodejs/src/node.h:573:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  573 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
/usr/include/nodejs/src/node.h:607:3: note: in expansion of macro ‘NODE_MODULE_X’
  607 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/bufferutil.cc:113:1: note: in expansion of macro ‘NODE_MODULE’
  113 | NODE_MODULE(bufferutil, init)
      | ^~~~~~~~~~~
In file included from /usr/include/nodejs/src/node.h:63,
                 from ../node_modules/nan/nan.h:49,
                 from ../src/bufferutil.cc:7:
/usr/include/nodejs/deps/v8/include/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/usr/include/nodejs/src/node_object_wrap.h:84:78:   required from here
/usr/include/nodejs/deps/v8/include/v8.h:9502:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
 9502 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/nodejs/deps/v8/include/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../node_modules/nan/nan_object_wrap.h:66:61:   required from here
/usr/include/nodejs/deps/v8/include/v8.h:9502:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
make: *** [bufferutil.target.mk:103: Release/obj.target/bufferutil/src/bufferutil.o] Ошибка 1
make: выход из каталога «/home/fedorov/LXD-UI/node_modules/bufferutil/build»
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/nodejs/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.4.0-28-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/fedorov/LXD-UI/node_modules/bufferutil
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 

> LXDui@1.0.0 postinstall /home/fedorov/LXD-UI
> npm run lint:fix


> LXDui@1.0.0 lint:fix /home/fedorov/LXD-UI
> eslint --ext .js,.vue -f ./node_modules/eslint-friendly-formatter --fix src test

npm WARN LXDui@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@2.1.1 (node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.1.1: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@1.0.1 (node_modules/7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/karma/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@3.0.3 (node_modules/bufferutil):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@3.0.3 install: `prebuild-install || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

audited 12712 packages in 8.07s

20 packages are looking for funding
  run `npm fund` for details

found 103 vulnerabilities (21 low, 45 moderate, 34 high, 3 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by lcherone** [comment]
Dunno looks just like https://github.com/nodejs/node-gyp/issues/1589

Try updating node, so bufferutil has a prebuilt binary or remove bufferutil from package.json, I'm not entirely sure its needed

```
"optionalDependencies": {
    "bufferutil": "^3.0.3"
}
```

**Comment by gglp** [comment]
I've upgraded node and removed "bufferutil" from package.json

fedorov@bequiet:~/LXD-UI$ node -v
v14.1.0

**Comment by gglp** [comment]
after
npm install
npm run build

error is stil present

fedorov@bequiet:~/LXD-UI$ ./build/LXDui-1.0.0-x86_64.AppImage 
installed: X-AppImage-BuildId=f577b3d0-5a01-11a8-0ac6-f33c83a5ffc7 image: X-AppImage-BuildId=502a1980-8aed-11aa-33a7-718708fce433
Gtk-Message: 17:17:36.991: Failed to load module "canberra-gtk-module"

(lxdui:75318): Pango-ERROR **: 17:17:37.177: Harfbuzz version too old (1.4.2)

**Comment by lcherone** [comment]
See https://github.com/lcherone/LXD-UI/issues/5 for other error
